Add PayPal contract renewal page
ezsystems/ezpersonalization-documentation pull request #6
Opened 2018-11-07 07:28 UTC by DominikaK

Ping @johaho for review

2018-11-07 08:27 UTC, MagdalenaZuba requested changes

2018-11-07 08:27 UTC, MagdalenaZuba commented on docs/ecommerce_plugins/paypal_contract_renewal.md
> +After this happens, you need to adding payment information again to renew the contract.
you need to add

2018-11-07 08:27 UTC, MagdalenaZuba commented on docs/ecommerce_plugins/paypal_contract_renewal.md
> +Step 3: A new window opens with the billwerk partner site. Billwerk is responsible for handling Personalization payments.
A new window in German opens

2018-11-07 08:27 UTC, MagdalenaZuba commented on mkdocs.yml
> +        - 'Renewing a PayPal contract': 'ecommerce_plugins/paypal_contract_renewal.md'
PayPal contract renewal - it's a title in the menu I would avoid 'a'

2018-11-07 09:08 UTC, DominikaK commented on docs/ecommerce_plugins/paypal_contract_renewal.md
> +Step 3: A new window opens with the billwerk partner site. Billwerk is responsible for handling Personalization payments.
@johaho, could you confirm that billwerk website is always in German, or do some customers have access to an English interface?

2018-11-07 09:10 UTC, MagdalenaZuba approved these changes

2018-11-13 09:13 UTC, ezpersonalization commented
Hi @DominikaK @MagdalenaZuba,
the page is fine. Go for it

2018-11-14 07:46 UTC, merged